import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  default: {
    width: '30%',
    backgroundColor: '#ECA3A3',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  defaultText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
  },
  primary: {
    width: '30%',
    backgroundColor: '#198C06',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
  },
  pickfriend :{
    width: '30%',
    backgroundColor: '#F1B0B0',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    padding : 10,
    marginBottom :10,
  },
  pickfriendText :{
    color: 'white',
    fontFamily: 'NPSfont_regular',
    fontSize : 15,
  },
  gotoisland :{
    width: '50%',
    backgroundColor: '#34D399',
    borderRadius: 8,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    position : 'absolute',
    top : '85%',
  },
  gotoislandText :{
    color: 'white',
    fontFamily: 'NPSfont_bold',
    fontSize : 20,
  },
  selectLeft: {
    width: '30%',
    backgroundColor: '#ECA3A3',
    borderRadius: 8,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal : 10,
  },
  selectLeftText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
  },
  selectRight: {
    width: '30%',
    backgroundColor: '#ECA3A3',
    borderRadius: 8,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal : 10,
  },
  selectRightText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
  },
});
