import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  default: {
    width: '30%',
    backgroundColor: '#5D9BFF',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  defaultText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
  },
  primary: {
    width: '30%',
    backgroundColor: '#198C06',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
  },
  animalName: {
    width: 170,
    backgroundColor: '#7ED3A1',
    borderRadius: 30,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  animalNameText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
  },
  carouselBtn: {
    width: 300,
    backgroundColor: '#7ED3A1',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickfriend: {
    width: '30%',
    backgroundColor: '#F1B0B0',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginBottom: 10,
  },
  pickfriendText: {
    color: 'white',
    fontFamily: 'NPSfont_regular',
    fontSize: 15,
  },
  gotoisland: {
    width: '50%',
    backgroundColor: '#34D399',
    borderRadius: 8,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: '85%',
  },
  ploggingRST: {
    width: '50%',
    backgroundColor: '#34D399',
    borderRadius: 8,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '5%',
    marginTop: '8%',
  },
  gotoislandText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
    fontSize: 20,
  },

  selectItem: {
    width: '30%',
    backgroundColor: '#ECA3A3',
    borderRadius: 8,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  selectItemText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
  },
  picnic: {
    width: '60%',
    backgroundColor: '#34D399',
    borderRadius: 20,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  picnicText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
    fontSize: 22,
  },
  region: {
    width: '60%',
    backgroundColor: '#F472B6',
    borderRadius: 10,
    height: '20%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nickname: {
    backgroundColor: '#5D9BFF',
    width: '60%',
    borderRadius: 10,
    height: '20%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userInfoText: {
    color: 'white',
    fontFamily: 'NPSfont_bold',
    fontSize : 22,
  },
  button: {
    borderRadius: 10,
    elevation: 2,
    marginTop: '20%',
    width: '50%',
    height: '25%',
    justifyContent: 'center',
    backgroundColor: '#2196F3',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'center',
  },
});
