import {StyleSheet} from 'react-native';
// 주석
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backButton: {
    backgroundColor: 'rgba(0,0,0,0.0)',
    position: 'absolute',
    justifyContent: 'center',
    width: '100%',
    top: 0,
    padding: 20,
  },
  backButtonStyle: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#fff',
    width: 100,
  },
  buttonContainer: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    zIndex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
    padding: 20,
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  camButton: {
    height: 80,
    width: 80,
    borderRadius: 40,
    backgroundColor: '#B2BEB5',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 4,
    borderColor: 'white',
  },
  retakeButton: {
    backgroundColor: '#fff',
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#77c3ec',
  },
  usePhotoButton: {
    backgroundColor: '#77c3ec',
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'white',
  },
  image: {
    width: '100%',
    height: '100%',
    aspectRatio: 9 / 16,
  },
  overlayContainer: {
    marginBottom: 10,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  overlayText: {
    position: 'absolute',
    zIndex: 2,
    fontSize: 13,
    color: 'white',
    textAlign: 'center',
    width: '100%',
    top: '40%',
    left: '8%',
  },
  overlayImage: {
    width: '25%',
    height: undefined,
    aspectRatio: 1,
    zIndex: 1,
    resizeMode: 'cover',
    // paddingLeft: '30%',
    // backgroundColor: 'black',
    transform: [{scaleX: -1}],
  },
  overlayRightImage: {
    width: '80%',
    zIndex: 1,
    transform: [{scaleY: -1}],
  },
  cameraIcon: {
    width: '80%',
    height: '80%',
  },
});

export default styles;
