spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # MySQL setting
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: [mariaDB_URL]
    username: [username]
    password: [password]
    hikari:
      maximum-pool-size: 20

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
      #        default_batch_fetch_size: 1000
      open-in-view: true
  jwt:
    prefix: 'Bearer'
    secret: [secret_code]
    token:
      access-expiration-time: 10800000
      refresh-expiration-time: 604800000
  data:
    redis:
      host: [host]
      port: [port]
      password: [password]

server:
  port: 5000
  servlet:
    context-path: /api

logging:
  level:
    com.com.vegetable: debug

# S3 image-upload
cloud:
  aws:
    s3:
      bucket: [bucket]
      url: [url]
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: [access-key]
      secret-key: [secret-key]
